// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Houeta/us-api-provider/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// EmployeeParserIface is an autogenerated mock type for the EmployeeParserIface type
type EmployeeParserIface struct {
	mock.Mock
}

// ParseEmployees provides a mock function with given fields: ctx
func (_m *EmployeeParserIface) ParseEmployees(ctx context.Context) ([]models.Employee, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ParseEmployees")
	}

	var r0 []models.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Employee, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Employee); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEmployeeParserIface creates a new instance of EmployeeParserIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeParserIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeParserIface {
	mock := &EmployeeParserIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
